name: pawssion
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  lottie: ^2.3.0
  flutter_signin_button: ^2.0.0
  modal_progress_hud_nsn: ^0.3.0
  google_sign_in: ^6.0.2
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.3
  mailer: ^6.0.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.7
  firebase_storage: ^11.0.16
  better_player: ^0.0.83
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CarterOne
      fonts:
        - asset: fonts/CarterOne-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

  assets:
    - assets/
    - .env
